src/java/com/corejsf/DatabaseBean.java
package com.corejsf;

import java.io.IOException;
import java.io.Serializable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.annotation.Resource;
import javax.enterprise.context.*;
import javax.inject.Named;
import javax.sql.DataSource;


@Named // or @ManagedBean
@ApplicationScoped
public class DatabaseBean implements Serializable{
    @Resource(name = "jdbc/quiz")
    private DataSource quizSource;

    private ArrayList<User> users;
    private User user;
    private String names;

    public void createUser(String name, String password)
            throws SQLException, IOException
    {
        String query = SQL.getSQL("create-user");
        Connection quizConnection = quizSource.getConnection();
        try
        {
            PreparedStatement statement =
                quizConnection.prepareStatement(query);
            statement.setString(1, name);
            statement.setString(2, password);
            statement.execute();

        }
        finally
        {
            quizConnection.close();
        }
    }

    public User getUser(String name)
      throws SQLException, IOException
    {
        String query = SQL.getSQL("user-query");
        Connection quizConnection = quizSource.getConnection();
        try
        {
            PreparedStatement statement =
                quizConnection.prepareStatement(query);
            statement.setString(1, name);
            ResultSet resultSet = statement.executeQuery();

            return buildUser(resultSet);
        }
        finally
        {
            quizConnection.close();
        }
    }

    public ArrayList<User> getUsers() throws SQLException, IOException {
        ArrayList<User> list = new ArrayList();

        Connection quizConnection = quizSource.getConnection();
        try
        {
            Statement statement =
                quizConnection.createStatement();
            ResultSet resultSet = statement.executeQuery(SQL.getSQL("get-users"));
            while(resultSet.next())
            {
                list.add(buildUserNoNext(resultSet));
            }
        }
        finally
        {
            quizConnection.close();
        }

        return list;
    }

    public boolean verifyUser(String name, String password)
            throws SQLException, IOException
    {
        boolean bool = false;
        ArrayList<User> list = getUsers();
        for(int i = 0; i < list.size(); i++)
        {
            if(list.get(i).getName().equals(name) &&
                    list.get(i).getPassword().equals(password))
                bool = true;
        }
        return bool;
    }

    public boolean userExists(String name) throws SQLException, IOException
    {
        if(getUsers() == null || getUsers().isEmpty())
            return false;
        ArrayList<User> list = getUsers();
        boolean bool = false;
        for(int i = 0; i < list.size(); i++)
        {
            if(list.get(i).getName().equals(name))
                bool = true;
        }
        return bool;
    }
  
    public void incrementScore(String username, String category, boolean right)
            throws SQLException, IOException
    {
        String queryTrue, queryFalse;
        String sqlTrue = appToDbAbb(category, true);
        String sqlFalse = appToDbAbb(category, false);
        Connection quizConnection = quizSource.getConnection();
        queryTrue = SQL.getSQL(sqlTrue);
        queryFalse = SQL.getSQL(sqlFalse);

        try
        {
            if(right)
            {
                PreparedStatement statement1 =
                    quizConnection.prepareStatement(queryTrue);
                statement1.setString(1, username);
                statement1.executeUpdate();
                
                PreparedStatement statement2 =
                    quizConnection.prepareStatement(queryFalse);
                statement2.setString(1, username);
                statement2.executeUpdate();
            }
            else
            {
                PreparedStatement statement3 =
                    quizConnection.prepareStatement(queryFalse);
                statement3.setString(1, username);
                statement3.executeUpdate();
            }
        }
        finally
        {
            quizConnection.close();
        }
    }

    public String[] getCategories() {
        String[] array = new String[4];

        array[0] = "Skateboarding";
        array[1] = "Football";
        array[2] = "Million $ Qs";
        array[3] = "Computer Science";

        return array;
    }

    public String getNamesString() throws SQLException, IOException{
        ArrayList<User> list = getUsers();
        names = "(";
        for(int i = 0; i < list.size(); i++)
        {
            names += list.get(i).getName();
            if((list.size() - i) != 1)
                names += ", ";
        }
        names += ")";

        return names;
    }

    private User buildUser(ResultSet resultSet)
      throws SQLException {
        int[][] array = new int[4][2];
        resultSet.next();
        String name = resultSet.getString("username");
        String password = resultSet.getString("password");
        array[0][0] = resultSet.getInt(4);
        array[0][1] = resultSet.getInt(5);
        array[1][0] = resultSet.getInt(6);
        array[1][1] = resultSet.getInt(7);
        array[2][0] = resultSet.getInt(8);
        array[2][1] = resultSet.getInt(9);
        array[3][0] = resultSet.getInt(10);
        array[3][1] = resultSet.getInt(11);

        return new User(name, password, array);
    }

    private User buildUserNoNext(ResultSet resultSet)
      throws SQLException {
        int[][] array = new int[4][2];
        String name = resultSet.getString("username");
        String password = resultSet.getString("password");
        array[0][0] = resultSet.getInt(4);
        array[0][1] = resultSet.getInt(5);
        array[1][0] = resultSet.getInt(6);
        array[1][1] = resultSet.getInt(7);
        array[2][0] = resultSet.getInt(8);
        array[2][1] = resultSet.getInt(9);
        array[3][0] = resultSet.getInt(10);
        array[3][1] = resultSet.getInt(11);

        return new User(name, password, array);
    }

    //Returns the table column name
    private String appToDbAbb(String category, boolean right) {
        if(category.equalsIgnoreCase("Skateboarding"))
        {
            if(right)
                return "cc1-update";
            else return "tc1-update";
        }
        else if(category.equalsIgnoreCase("Football"))
        {
            if(right)
                return "cc2-update";
            else return "tc2-update";
        }
        else if(category.equalsIgnoreCase("Million $ Qs"))
        {
            if(right)
                return "cc3-update";
            else return "tc3-update";
        }
        else
        {
            if(right)
                return "cc4-update";
            else return "tc4-update";
        }
    }
}

src/java/com/corejsf/QuizBean.java
package com.corejsf;

import java.io.IOException;
import java.io.Serializable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.enterprise.context.Conversation;
import javax.inject.Named;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;

@Named // or @ManagedBean
@ConversationScoped
public class QuizBean implements Serializable {
   private int currentProblem;
   private int tries;
   private String response = "",  categoryString = "",
           correctAnswer = "", currentUser = "", error = "default error";
   private CategoryBean category;
   private boolean correct;
   private boolean done = false;
   private boolean start = true;
   private String[] categoryArray = {"Skateboarding", "Football",
                                        "Million $ Qs", "Computer Science"};
   private String[] currentUserScore;
   private @Inject Conversation conversation;
   private @Inject DatabaseBean database;

   // List of questions for all of the mini quizes
   private ArrayList<ProblemBean> problems = new ArrayList<ProblemBean>(Arrays.asList(
      new ProblemBean("Skateboarding",
         "What trick is generally considered the hardest?", "Kickflip", "Ollie",
          "360 Flip", "360 Flip"),
      new ProblemBean("Skateboarding",
         "What is the world record ollie height in inches?", "38", "44.5", "51.5",
         "44.5"),
      new ProblemBean("Skateboarding",
         "Who has won the most gold medals?", "Shaun White", "Tony Hawk", "Ryan Sheckler",
         "Tony Hawk"),
      new ProblemBean("Football",
         "Who threw a record six touchdown passes in a Super Bowl?", "Steve Young",
         "Brett Farve", "Eli Manning",
         "Steve Young"),
      new ProblemBean("Football",
         "What NFL team was the first to win the Vince Lombardi trophy five times?",
          "Packers", "Colts", "49ers",
         "49ers"),
      new ProblemBean("Football",
         "What team was led to Super Bowls VII, and VIII by their no-name defense?",
          "Steelers", "Jets", "Dolphins",
         "Dolphins"),
      new ProblemBean("Million $ Qs",
         "Which king was married to Eleanor of Aquitaine?", "Henry 1", "Richard 5",
         "Henry 2",
         "Henry 2"),
      new ProblemBean("Million $ Qs",
         "Which of these U.S presidents appeared on the television series Laugh-in?",
         "Jimmy Carter", "Richard Nixon", "Gerald Ford",
         "Richard Nixon"),
      new ProblemBean("Million $ Qs",
         "What scientist first determined that human sight results from images"
         + " projected onto the retina?", "Galileo", "Newton", "Kepler",
         "Kepler"),
      new ProblemBean("Computer Science",
         "If you need to sort a very large list of integers (billions), "
         + "what efficient sorting algorithm would be best?", "Quick", "Merge", "Shell",
         "Quick"),
      new ProblemBean("Computer Science",
         "What year was Google founded?", "1995", "1998", "2001",
         "1998"),
      new ProblemBean("Computer Science",
         "What was the first full-length computer generated feature film?",
         "A Bugs Life", "Toy Story", "Antz",
         "Toy Story")));

   //When a category is selected this method creates a new CategoryBean
   //with the questions from that category.
   public String categoryAction() {
        try {
            updateCurrentUserScore();
        } catch (SQLException ex) {
            setError(ex.getSQLState() + " " + ex.toString());
            ex.printStackTrace(System.err);
            return "error";
        } catch (IOException ex) {
            setError(ex.toString());
            ex.printStackTrace(System.err);
            return "error";
        }
        start = true;
        done = false;
        String str = categoryString;
        ArrayList<ProblemBean> list = new ArrayList<ProblemBean>(3);

        response = "";

        //Find specific category questions out of the list of all questions
        for(int i = 0; i < problems.size(); i++)
        {
            if(problems.get(i).getCategory().equals(str))
                list.add(problems.get(i));
        }

        this.category = new CategoryBean(str, list);

        //Always navigates to first.xhtml
        return "quiz";
   }

   //Checks to see if the user guessed correctly
   //and sets up the program for the next question
   //or navigates to done.xhtml
   public String answerAction() {
        start = false;
        if (category.getProblem().isCorrect(response)) {
            correct = true;
            try {
                database.incrementScore(currentUser, categoryString, true);
            } catch (SQLException ex) {
                error = ex.getSQLState() + ex.toString();
                return "error";
            } catch (IOException ex) {
                error = ex.toString();
                return "error";
            }

            try {
                updateCurrentUserScore();
            } catch (SQLException ex) {
                setError(ex.getSQLState() + " " + ex.toString());
                ex.printStackTrace(System.err);
                return "error";
            } catch (IOException ex) {
                setError(ex.toString());
                ex.printStackTrace(System.err);
                return "error";
            }

            response = "";
            category.next();
            if(category.hasNext()) {
                nextProblem();
                return "quiz";
            }
            else {
                currentProblem++;
                done = true;
                return "quiz";
            }
        }
        else
        {
            response = "";
            correct = false;
            try {
                database.incrementScore(currentUser, categoryString, false);
            } catch (SQLException ex) {
                error = ex.getSQLState() + ex.toString();
                return "error";
            } catch (IOException ex) {
                error = ex.toString();
                return "error";
            }

            try {
                updateCurrentUserScore();
            } catch (SQLException ex) {
                setError(ex.getSQLState() + " " + ex.toString());
                ex.printStackTrace(System.err);
                return "error";
            } catch (IOException ex) {
                setError(ex.toString());
                ex.printStackTrace(System.err);
                return "error";
            }

            category.next();
            if (category.hasNext()) {
                nextProblem();
                return "quiz";
            }
            else {
                currentProblem++;
                 done = true;
                 return "quiz";
            }
        }
   }

   //Sets up quizbean to handle another quiz and
   //returns the user to category.xhtml
   public String startOverAction() {
       try {
            updateCurrentUserScore();
        } catch (SQLException ex) {
            setError(ex.getSQLState() + " " + ex.toString());
            ex.printStackTrace(System.err);
            return "error";
        } catch (IOException ex) {
            setError(ex.toString());
            ex.printStackTrace(System.err);
            return "error";
        }
       currentProblem = 0;
       categoryString = "";
       response = "";
       return "category";
   }

   //Refreshes debug.xhtml
   public String refreshAction() {
       return "debug";
   }

   //Returns an array of the current users scores
   //formated in the style of "correct" + "/" + "trys"
   public String[] getCurrentUserScore() {
       return currentUserScore;
   }

   //Sets the current user and starts the conversation
   public void setCurrentUser(String name) {
       currentUser = name;
       conversation.begin();
   }

   //Returns the current users name
   public String getCurrentUser() {
       return currentUser;
   }

   //Returns a User object of current user
   public User getCurrentUserObj() throws SQLException, IOException {
       return database.getUser(currentUser);
   }

   //Returns current category
   public CategoryBean getCategory() {
       return category;
   }

   //Sets the current category
   public void setCategoryString(String str) {
       categoryString = str;
   }

   public String getCategoryString() {
       return categoryString;
   }

   //Returns the category array
   public String[] getCategoryArray() {
       return categoryArray;
   }

   //Returns current question
   public String getQuestion() {
       if(category.hasNext())
           return category.getProblem().getQuestion();
       else return "error";
   }

   //Returns answer to current question
   public String getAnswer() {
       return category.getProblem().getAnswer();
   }

   public String getPrevAnswer() {
       return category.getPrevProblem().getAnswer();
   }

   //Returns the users response to the question
   public String getResponse() {
       return response;
   }

   //Sets the users response to the question
   public void setResponse(String newValue) {
       response = newValue;
   }

   //Returns current problem index
   public int getCurrentProblem() {
       return currentProblem;
   }

   //Sets current problem
   public void setCurrentProblem(int x) {
       currentProblem = x;
   }

   //Returns if the user got the last question correct
   public boolean getCorrect()
   {
       return correct;
   }

   //Returns if the user is done with the quiz
   public boolean getDone()
   {
       return done;
   }

   //Returns if the user is on the first question
   public boolean getStart()
   {
       return start;
   }

   //Returns the current error string
   public String getError() {
       return error;
   }

   //Sets the error string to be displayed in error.xhtml
   public void setError(String str) {
       error = str;
   }

   //Gets ready to move onto the next problem
   private void nextProblem() {

web/category.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
   <h:head>
      <h:outputStylesheet library="css" name="styles.css"/>
      <title>#{msgs.title}</title>
   </h:head>
   <h:body>
      <h:form>
            <p class="title">#{msgs.title}</p>
             <h:selectOneListbox styleClass="menu"
                                 value="#{quizBean.categoryString}"
                                 required="true"
                                 requiredMessage="Selection is required.">
                 <f:selectItems value="#{quizBean.categoryArray}"/>
            </h:selectOneListbox>
             <p>
             <h:commandButton value="#{msgs.startQuiz}"
                              action="#{quizBean.categoryAction}"
                              styleClass="button"/>
             </p>
      </h:form>
   </h:body>
</html>

web/debug.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <h:outputStylesheet library="css" name="styles.css"/>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <p>
            <p class="title">#{msgs.debug}</p>
            <p>
                <h:commandButton value="#{msgs.refresh}"
                                action="#{quizBean.refreshAction}"
                                styleClass="button"/>
            </p>
            <p class="text">The current login names are #{databaseBean.namesString}.</p>
        </p>

        <table class="table">
            <tr> <!-- column header row -->
                <td class="header">Name</td> <!-- corner entry -->
                <ui:repeat value="#{databaseBean.categories}" var="categories">
                    <td class="header">#{categories}</td> <!-- column header entries -->
                </ui:repeat>
            </tr>
            <ui:repeat value="#{databaseBean.users}" var="user">
                <tr> <!-- main table rows -->
                    <td class="header">#{user.name}</td> <!-- row header entry -->
                    <ui:repeat value="#{user.scoresString}" var="score">
                        <td class="entry">#{score}</td>
                    </ui:repeat>
                </tr>
            </ui:repeat>
        </table>

        <p>
                <h:commandButton value="Return to Login"
                                action="index?faces-redirect=true"
                                styleClass="button"
                                immediate ="true"/>
        </p>

    </h:body>
</html>

web/error.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <h:outputStylesheet library="css" name="styles.css"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <p class="title">Error Page:</p>
        <p>
            #{quizBean.error}
        </p>
    </h:body>
</html>

web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <h:outputStylesheet library="css" name="styles.css"/>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <h:form>
                <p class="title">#{msgs.login}</p>
                <p class="text">#{msgs.register}</p>
                <p>
                    <h:commandButton value="Register"
                                     action="register?faces-redirect=true"
                                     immediate="true"
                                     styleClass="button"
                                     />
                </p>
        </h:form>
        <h:form>
                <p>
                    Username <h:inputText value="#{loginBean.username}"
                                           required="true"
                                           requiredMessage="A name is required"/>
                </p>
                <p>
                    Password <h:inputSecret value="#{loginBean.password}"
                                           required="true"
                                           requiredMessage="A password is required"/>
                </p>
                <p>
                <h:commandButton value="Login"
                                action="#{loginBean.loginAction}"
                                styleClass="button"/>
                </p>
                <p>
                    <h:panelGroup rendered="#{!loginBean.verified}"
                                  styleClass="error">
                        #{msgs.invalid}
                    </h:panelGroup>
                </p>
        </h:form>
    </h:body>
</html>

web/quiz.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <h:outputStylesheet library="css" name="styles.css"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <title> #{msgs.title}</title>
    </h:head>
    <h:body>
        <h:form>
        <p>
            <p class="title">#{quizBean.category.name}
                Trivia Quiz</p>

            <p class="text"> #{quizBean.currentUser}'s current scores:</p>
            <table class="table">
                <tr> <!-- column header row -->
                    <ui:repeat value="#{databaseBean.categories}" var="categories">
                        <td class="header">#{categories}</td> <!-- column header entries -->
                    </ui:repeat>
                </tr>
                <tr> <!-- main table rows -->
                    <ui:repeat value="#{quizBean.currentUserScore}" var="score">
                        <td class="entry">#{score}</td>
                    </ui:repeat>
                </tr>
            </table>


            <h:panelGroup rendered="#{!quizBean.start}">
            <p>
            <h:outputFormat value="#{msgs.correctAnswer}" rendered ="#{!quizBean.correct}"
                            styleClass="text">
                <f:param value="#{quizBean.prevAnswer}"/>
            </h:outputFormat>

            <h:outputFormat value="#{msgs.correct}" rendered ="#{quizBean.correct}"
                            styleClass="text">
            </h:outputFormat>
            </p>
            </h:panelGroup>


            <h:panelGroup rendered="#{!quizBean.done}">
            <p>
                <p class="text">#{msgs.question} </p>
                <p class="text">#{quizBean.question}</p>
            </p>
                <p>
                <h:selectOneRadio value="#{quizBean.response}" layout="pageDirection"
                                  styleClass="radio"
                                  required="true"
                                  requiredMessage="Selection is required.">
                    <f:selectItems value="#{quizBean.category.problem.possibleAnswers}"/>
                </h:selectOneRadio>
                </p>
            <p>
            <h:commandButton value="#{msgs.checkAnswer}"
                             action="#{quizBean.answerAction}"
                             styleClass="button"/>
            </p>
            </h:panelGroup>

            <h:panelGroup rendered="#{quizBean.done}"
                          styleClass="text">
                <p> Congratulations you have completed the
                    #{quizBean.category.name} Trivia Quiz!</p>
                <p>
                <h:commandButton value="#{msgs.anotherQuiz}"
                             action="#{quizBean.startOverAction}"
                             styleClass="button"/>
                </p>
            </h:panelGroup>
        </p>
        </h:form>
    </h:body>
</html>

web/register.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <h:outputStylesheet library="css" name="styles.css"/>
        <title>#{msgs.title}</title>
    </h:head>
    <h:body>
        <h:form>
            <p>
                <p class="title">#{msgs.registerTitle}</p>
                <p>
                    Username <h:inputText value="#{registerBean.username}"
                                           required="true"
                                           requiredMessage="A name is required"/>
                </p>
                <p>
                    Password <h:inputSecret value="#{registerBean.password}"
                                           required="true"
                                           requiredMessage="A password is required"/>
                </p>
                <p>
                    Password <h:inputSecret value="#{registerBean.passwordCheck}"
                                           required="true"
                                           requiredMessage="A duplicate of the password is required"/>
                </p>
                <p>
                <h:commandButton value="Register"
                                action="#{registerBean.registerAction}"
                                styleClass="button"/>
                </p>
                <p>
                    <h:panelGroup rendered="#{!registerBean.verified}"
                                  styleClass="error">
                        #{msgs.mismatch}
                    </h:panelGroup>
                </p>
                <p>
                    <h:panelGroup rendered="#{registerBean.sameName}"
                                  styleClass="error">
                        #{msgs.nameTaken}
                    </h:panelGroup>
                </p>
            </p>
        </h:form>
    </h:body>
</html>